name: Server Frontend Deployment - Triplergames.com
on:
  push:
    branches: [ "production" ]
  workflow_dispatch:
  
jobs:
  checkout-frontend:
    runs-on: frontend
    steps:
      - name: Get server repository
        uses: actions/checkout@v4
      - name: Update node
        uses: actions/setup-node@v4
        with:
          node-version: 18.13
        
  build-frontend:
      runs-on: frontend
      needs: checkout-frontend
      steps:
        - name: Build frontend
          run: | 
            npm install
            ng build

  move-frontend:
      runs-on: frontend
      needs: build-frontend
      steps:
        - name: Move frontend to folder
          run: mv dist\ /var/www/triplergames.com/html
